sonar.projectKey=d-fine_DatalandQALab
sonar.organization=d-fine

sonar.sources=qa_lab,qa_lab_monitor
sonar.tests=qa_lab/tests,qa_lab_monitor/tests

sonar.exclusions=**/tests/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=true
