from openai.types.chat import ChatCompletionMessageToolCall
from openai.types.chat.chat_completion import (
            ChatCompletion,
            ChatCompletionMessage,
            Choice,
)
from openai.types.chat.chat_completion_message_tool_call import Function

E2E_AZURE_DOCUMENT_INTELLIGENCE_MOCK = "134"
E2E_AZURE_OPEN_AI_TEMPLATE_1 = ChatCompletion(
    id="test1",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments='{"1": "No", "2": "No", "3": "No", "4": "Yes", "5": "Yes", "6": "No"}',
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_2_REVENUE = ChatCompletion(
    id="test2",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_2_CAPEX = ChatCompletion(
    id="test2",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_3_REVENUE = ChatCompletion(
    id="test3",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_3_CAPEX = ChatCompletion(
    id="test3",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_4_REVENUE = ChatCompletion(
    id="test4",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_4_CAPEX = ChatCompletion(
    id="test4",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_5_REVENUE = ChatCompletion(
    id="test5",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
E2E_AZURE_OPEN_AI_TEMPLATE_5_CAPEX = ChatCompletion(
    id="test5",
    choices=[
        Choice(
            finish_reason="stop",
            index=0,
            message=ChatCompletionMessage(
                role="assistant",
                tool_calls=[
                    ChatCompletionMessageToolCall(
                        id="call_EEG3soMwEWVsq3HVX3MGCdcE",
                        function=Function(
                            arguments="""{
                            "answer_value_CCM+CCA%_row1":"-1","answer_value_CCM%_row1":"-1","answer_value_CCA%_row1":"-1",
                            "answer_value_CCM+CCA%_row2":"-1","answer_value_CCM%_row2":"-1","answer_value_CCA%_row2":"-1",
                            "answer_value_CCM+CCA%_row3":"-1","answer_value_CCM%_row3":"-1","answer_value_CCA%_row3":"-1",
                            "answer_value_CCM+CCA%_row4":"-1","answer_value_CCM%_row4":"-1","answer_value_CCA%_row4":"-1",
                            "answer_value_CCM+CCA%_row5":"-1","answer_value_CCM%_row5":"-1","answer_value_CCA%_row5":"-1",
                            "answer_value_CCM+CCA%_row6":"-1","answer_value_CCM%_row6":"-1","answer_value_CCA%_row6":"-1",
                            "answer_value_CCM+CCA%_row7":"17","answer_value_CCM%_row7":"17","answer_value_CCA%_row7":"-1",
                            "answer_value_CCM+CCA%_row8":"-1","answer_value_CCM%_row8":"-1","answer_value_CCA%_row8":"-1"
                            }""",
                            name="requested_information_precisely_found_in_relevant_documents"
                        ),
                        type="function"
                    )
                ]
            ),
            content_filter_results={}
        )
    ],
    created=0,
    model="test",
    object="chat.completion"
)
