---
- name: Configure an OTC ubuntu server for a Dataland QALab Deployment
  hosts: all
  become: true
  tasks:
    - name: Update packages on the system
      ansible.builtin.include_role:
        name: systemupdate

    - name: Configure SSH Server
      ansible.builtin.include_role:
        name: configuressh

    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: false
        docker_users:
          - 'ubuntu'

    - name: Configure authoirzed SSH Keys
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ authorized_ssh_keys }}"  
