---
- name: Update the system using apt, rebooting if required
  become: true
  block:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all packages on server
      ansible.builtin.apt:
        upgrade: dist

    - name: Check if a reboot is required
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required

    - name: Reboot if required
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: true
